### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by wyaily** [k0k1a/EOrder#1]
您好我想问您一下这个的详细步骤，可以留个联系方式嘛 谢谢 盼复！

**Comment by k0k1a** [comment]
除了pic是存readme的图片点，另外的目录都是独立点项目，分别打开就行了。springboot点项目修改一下配置。小程序的去看一下微信小程序官网

**Comment by wyaily** [comment]
好的 谢谢哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月23日(星期四) 晚上8:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [k0k1a/EOrder] 请教问题 (Issue #1)





 
除了pic是存readme的图片点，另外的目录都是独立点项目，分别打开就行了。springboot点项目修改一下配置。小程序的去看一下微信小程序官网
