### ISSUE TITLE
web管理端登录不进去显示跨域问题

### ISSUE THREAD

**Issue by wyaily** [k0k1a/EOrder#4]

**Comment by k0k1a** [comment]
92024109936

**Comment by k0k1a** [comment]
1. 重新拉一下代码，我改了些东西

**Comment by k0k1a** [comment]
1.重新拉一下代码
2.管理端账号92024109936，exR4HT7jzh7QPeRx

**Comment by wyaily** [comment]
好的，我先试试 谢谢您！

**Comment by wyaily** [comment]
您好，还是登不进去

**Comment by wyaily** [comment]
显示的Access to XMLHttpRequest at 'http://localhost:8080/eorder/admin/login' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.这个代码

**Comment by wyaily** [comment]
显示的Access to XMLHttpRequest at 'http://localhost:8080/eorder/admin/login' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.这个代码
